### ISSUE TITLE
Please add virtual desktops / workspaces

### ISSUE THREAD

**Issue by JGCYASYS** [alx210/emwm#1]
I think this is a really cool windows manager. I have just one request. Can you implement virtual desktops / workspaces like how FVWM and CTWM do it? I would make this my daily wm if you did so. Thanks.

**Comment by alx210** [comment]
The code for multiple workspaces is actually there, but won't currently build, due to third party IPC related dependencies. It's on my to-do list to clean it up and get it working.

**Comment by JGCYASYS** [comment]
What is your current to-do list? If you could list the IPC related dependencies maybe I or someone else could help.

**Comment by alx210** [comment]
Well, all the code that was ifdef'd out as WSM (there is quite a bit of it) needs to be revised. Current workspaces implementation depends on obsolete ToolTalk IPC, and hence must be rewritten using simple X property mechanism that is EWMH compliant. If anybody likes to dig trough it, patches are welcome :)

**Comment by JGCYASYS** [comment]
All you need someone to do is just replace the ifdef'd out WSM code? That's it? And what modern X property mechanism would you recommend be used instead?
